# Generated by Django 5.1.5 on 2025-04-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='place_overall',
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
