# Generated by Django 5.1.5 on 2025-04-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0004_alter_voter_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='party_affiliation',
            field=models.CharField(max_length=2),
        ),
    ]
