# Generated by Django 5.1.5 on 2025-04-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0005_alter_voter_party_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='apartment_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
