# Generated by Django 5.1.5 on 2025-04-18 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Game', 'Game'), ('Stream', 'Stream'), ('Tool', 'Tool'), ('Mod', 'Mod')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='works/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_type', models.CharField(choices=[('Game Creator', 'Game Creator'), ('Streamer', 'Streamer'), ('Musician', 'Musician'), ('Designer', 'Designer')], max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('website_or_channel', models.URLField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='project.tag')),
                ('featured_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.work')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('bookmarked_profiles', models.ManyToManyField(blank=True, related_name='bookmarked_by', to='project.profile')),
                ('interests', models.ManyToManyField(blank=True, to='project.tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_type', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('website_or_channel', models.URLField()),
                ('reason_for_submission', models.TextField()),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user')),
            ],
        ),
    ]
