# Generated by Django 5.1.5 on 2025-04-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('Game Creator', 'Game Creator'), ('Streamer', 'Streamer'), ('Both', 'Both')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_or_channel',
            field=models.URLField(blank=True, null=True),
        ),
    ]
