# Generated by Django 5.1.5 on 2025-04-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('Game Creator', 'Game Creator'), ('Streamer', 'Streamer'), ('Youtuber', 'Youtuber')], max_length=50),
        ),
    ]
