# Generated by Django 5.1.5 on 2025-05-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('Game Creator', 'Game Creator'), ('Streamer', 'Streamer'), ('Youtuber', 'Youtuber'), ('Streamer/Youtuber', 'Streamer/Youtuber')], max_length=50),
        ),
    ]
