# Generated by Django 5.1.5 on 2025-05-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_profile_photo_alter_submission_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='approved',
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
