# Generated by Django 5.1.5 on 2025-05-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_submission_approved_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='tags',
            field=models.ManyToManyField(blank=True, to='project.tag'),
        ),
    ]
