# Generated by Django 5.1.5 on 2025-05-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_profile_created_creator_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='website_or_channel',
            field=models.URLField(blank=True, null=True),
        ),
    ]
