# Generated by Django 5.1.5 on 2025-05-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_submission_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='featured_work',
        ),
        migrations.AddField(
            model_name='profile',
            name='featured_works',
            field=models.ManyToManyField(blank=True, to='project.work'),
        ),
    ]
