# Generated by Django 5.1.5 on 2025-05-01 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_profile_featured_work_profile_featured_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Game', 'Game'), ('Stream', 'Stream'), ('Tool', 'Tool'), ('Mod', 'Mod')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='submitted_works/')),
                ('link', models.URLField()),
                ('approved', models.BooleanField(default=False)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.profile')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userprofile')),
            ],
        ),
    ]
