# Generated by Django 5.1.5 on 2025-05-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_worksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
