# Generated by Django 5.1.5 on 2025-03-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_image_caption_alter_image_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusimage',
            old_name='image',
            new_name='image_file',
        ),
    ]
